name: ca

services:
  ca:
    container_name: ca
    build:
      context: certificates
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/home/step
    ports:
      - 443:9000
    environment:
      - DOCKER_STEPCA_INIT_NAME=MMLAB
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,mmlab-ca.lmss.cc
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_PASSWORD=password
    extra_hosts:
      - host.docker.internal:host-gateway
    dns:
    - 172.28.0.2
  coordinator:
    profiles: [donotstart]
    container_name: coordinator
    image: ghcr.io/open-mpic/coordinator:latest
    restart: unless-stopped
    configs:
      - source: coordinator_config
        target: /app/config/app.conf
      - source: log_config
        target: /app/config/log_config.yaml
      - source: uvicorn_config
        target: /app/config/uvicorn_config.yaml
    volumes:
      - ./resources:/app/resources
    dns:
      - 172.28.0.2
  unbound:
    container_name: unbound
    image: ghcr.io/open-mpic/unbound:latest
    restart: unless-stopped
    #volumes:
    #  - ./unbound_config/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    networks:
      default:
        ipv4_address: 172.28.0.2 # static IP address within acceptable range

configs:
  coordinator_config:
    content: |
      perspectives={"ohio":{"caa_endpoint_info":{"url":"http://mmlab-va2.lmss.cc/caa"},"dcv_endpoint_info":{"url":"http://mmlab-va2.lmss.cc/dcv"}},"seoul":{"caa_endpoint_info":{"url":"http://mmlab-va1.lmss.cc/caa"},"dcv_endpoint_info":{"url":"http://mmlab-va1.lmss.cc/dcv"}}}
      default_perspective_count=2
      absolute_max_attempts=2
      hash_secret=hash_secret
      http_client_timeout_seconds=30
      http_client_keepalive_timeout_seconds=120
  log_config:
    file: ../common/common_config/log_config.yaml
  uvicorn_config:
    file: ../common/common_config/uvicorn_config.yaml