name: ca

services:
  ca:
    container_name: ca
    build:
      context: certificates
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/home/step
    ports:
      - 9000:9000
    environment:
      - DOCKER_STEPCA_INIT_NAME=MMLAB
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,mmlab-ca.lmss.cc
      - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
      - DOCKER_STEPCA_INIT_ACME=true
      - DOCKER_STEPCA_INIT_PASSWORD=password
  coordinator:
    container_name: coordinator
    # image: ghcr.io/open-mpic/coordinator:latest
    build:
      context: ../common/open-mpic-containers/api-implementation
      args:
        SERVICE_PATH: "src/mpic_coordinator_service"
    restart: unless-stopped
    configs:
      - source: coordinator_config
        target: /app/config/app.conf
      - source: log_config
        target: /app/config/log_config.yaml
      - source: uvicorn_config
        target: /app/config/uvicorn_config.yaml
    volumes:
      - ./resources:/app/resources
configs:
  coordinator_config:
    content: |
      perspectives={"ohio":{"caa_endpoint_info":{"url":"http://caa.mmlab-va2.lmss.cc"},"dcv_endpoint_info":{"url":"http://dcv.mmlab-va2.lmss.cc"}},"seoul":{"caa_endpoint_info":{"url":"http://caa.mmlab-va1.lmss.cc"},"dcv_endpoint_info":{"url":"http://dcv.mmlab-va1.lmss.cc"}}}
      default_perspective_count=2
      absolute_max_attempts=2
      hash_secret=hash_secret
      http_client_timeout_seconds=30
      http_client_keepalive_timeout_seconds=120
  log_config:
    file: ../common/common_config/log_config.yaml
  uvicorn_config:
    file: ../common/common_config/uvicorn_config.yaml